FROM node:20-alpine

ARG SHOPIFY_STORE=qa.shopify.firstalert.com
ARG SFTP_HOST=sftp.igxfer.com
ARG SFTP_PORT=22
ARG SFTP_USER=BRNDGR1I1
ARG SFTP_REMOTE_PATH=/orders.csv

ENV SHOPIFY_STORE=${SHOPIFY_STORE} \
    SHOPIFY_ACCESS_TOKEN=${_SHOPIFY_ACCESS_TOKEN} \
    SFTP_HOST=${SFTP_HOST} \
    SFTP_PORT=${SFTP_PORT} \
    SFTP_USER=${SFTP_USER} \
    SFTP_PASSWORD=${_SFTP_PASSWORD} \
    SFTP_REMOTE_PATH=${SFTP_REMOTE_PATH}



WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 8080
CMD ["npm", "start"]